// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"chat/hooks/useStreaming":{"path":"chat/hooks/useStreaming","id":"chat/hooks/useStreaming","parentId":"@@/global-layout"},"chat/hooks/useChat":{"path":"chat/hooks/useChat","id":"chat/hooks/useChat","parentId":"@@/global-layout"},"chat/index":{"path":"chat","id":"chat/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'chat/hooks/useStreaming': React.lazy(() => import(/* webpackChunkName: "src__pages__chat__hooks__useStreaming" */'../../../src/pages/chat/hooks/useStreaming.ts')),
'chat/hooks/useChat': React.lazy(() => import(/* webpackChunkName: "src__pages__chat__hooks__useChat" */'../../../src/pages/chat/hooks/useChat.ts')),
'chat/index': React.lazy(() => import(/* webpackChunkName: "src__pages__chat__index" */'../../../src/pages/chat/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/workSpace/Prodigal/prodigal-ai-travel/prodigal-travel-web/src/layouts/index.tsx')),
},
  };
}
